apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wur3osmyf-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:8e6f5fab22a1f3408901cdf486fbf78ca47155ca@sha256:738755b91b5c624c98c86dd3e535a33305f516320ad27bb5a7265c6a51395cf5
          name: container-image
