apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wur3osmyf-python
  janus-idp.io/tekton: wur3osmyf-python
  backstage.io/kubernetes-id: wur3osmyf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wur3osmyf-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
